# This is a basic workflow to help you get started with Actions

name: PHPStan

# Controls when the action will run. 
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  phpstan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Startup
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      # Checkout pmmp/PocketMine-MP
      - name: wget PocketMine-MP
        uses: wei/wget@v1
        with:
          args: -O vendor/PocketMine-MP.phar https://github.com/pmmp/PocketMine-MP/releases/latest/download/PocketMine-MP.phar
      # Checkout https://github.com/Muqsit/InvMenu
      - name: Checkout InvMenu
        uses: actions/checkout@v2
        with:
          repository: Muqsit/InvMenu
          ref: master
          path: vendor/InvMenu
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run PHPStan
        uses: larryTheCoder/pmmp-phpstan-action@master
        with:
          phpstan-config: phpstan.neon